'use client';

import React, { useState } from 'react';
import { Table, Button, Popconfirm, Tag, Space, Typography, Card, Modal, Form, Input, Select, message } from 'antd';
import { EditOutlined, DeleteOutlined, PlusOutlined, LinkOutlined } from '@ant-design/icons';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { createService, updateService, deleteService, getService } from './actions';
import ResponsiveTable from '@/components/ResponsiveTable';

const { Title } = Typography;
const { TextArea } = Input;

const plusJakartaSans = Plus_Jakarta_Sans({ 
  subsets: ['latin'], 
  weight: ['600', '700'],
  display: 'swap',
});

const ICON_OPTIONS = [
  { value: '☁️', label: 'Cloud' },
  { value: '🌐', label: 'Web' },
  { value: '📱', label: 'Mobile' },
  { value: '🛡️', label: 'Security' },
  { value: '📊', label: 'Data / Analytics' },
  { value: '🤖', label: 'AI / Machine Learning' },
  { value: '⚙️', label: 'DevOps' },
  { value: '💼', label: 'Consulting' },
  { value: '⚡', label: 'Performance' },
  { value: '🔗', label: 'Integration' },
  { value: '🚀', label: 'Startup' },
  { value: '🖥️', label: 'Desktop' },
];

export interface ServiceData {
  id: string;
  title: string;
  status: string;
  updatedAt: Date;
}

interface ServicesTableProps {
  data: ServiceData[];
}

export default function ServicesTable({ data }: ServicesTableProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form] = Form.useForm();
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [useCustomIcon, setUseCustomIcon] = useState(false);

  const handleOpenModal = async (record?: ServiceData) => {
    setIsModalOpen(true);
    if (record) {
      setEditingId(record.id);
      setIsSlugAutoGenerated(false);
      const res = await getService(record.id);
      if (res.success && res.data) {
        const fullData = res.data;
        // Determine if image is a custom URL or an emoji preset
        const img = fullData.image || '';
        const isCustom = img && !ICON_OPTIONS.some(o => o.value === img);
        setUseCustomIcon(!!isCustom);
        setTimeout(() => form.setFieldsValue({
          ...fullData,
          image: isCustom ? '' : img,
          customIcon: isCustom ? img : '',
        }), 0);
      } else {
        setTimeout(() => form.setFieldsValue(record), 0);
      }
    } else {
      setEditingId(null);
      setIsSlugAutoGenerated(true);
      setUseCustomIcon(false);
      setTimeout(() => form.resetFields(), 0);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    form.resetFields();
    setEditingId(null);
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isSlugAutoGenerated) {
      const value = e.target.value;
      const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
      form.setFieldsValue({ slug });
    }
  };

  const handleDelete = async (id: string) => {
    const res = await deleteService(id);
    if (res.success) {
      message.success('Layanan berhasil dihapus');
    } else {
      message.error(res.error || 'Gagal menghapus layanan');
    }
  };

  const onFinish = async (values: any) => {
    const imageValue = useCustomIcon ? (values.customIcon || null) : (values.image || null);

    const submitData = {
      ...values,
      image: imageValue,
    };
    delete submitData.customIcon;

    let res;
    if (editingId) {
      res = await updateService(editingId, submitData);
    } else {
      res = await createService(submitData);
    }

    if (res.success) {
      message.success('Layanan berhasil disimpan!');
      handleCloseModal();
    } else {
      message.error(res.error || 'Gagal menyimpan layanan');
    }
  };

  const columns = [
    {
      title: 'Nama Layanan',
      dataIndex: 'title',
      key: 'title',
      render: (text: string) => <span className="font-semibold text-slate-800">{text}</span>,
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => {
        const color = status === 'PUBLISHED' ? 'green' : status === 'DRAFT' ? 'gold' : 'blue';
        return <Tag color={color} className="font-semibold px-3 py-1 rounded-md tracking-wide">{status}</Tag>;
      },
    },
    {
      title: 'Updated At',
      dataIndex: 'updatedAt',
      key: 'updatedAt',
      render: (date: Date) => (
        <span className="text-slate-500 font-medium">
          {new Date(date).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}
        </span>
      ),
    },
    {
      title: 'Aksi',
      key: 'action',
      render: (_: any, record: ServiceData) => (
        <Space size="small">
          <Button 
            type="text" 
            icon={<EditOutlined />} 
            className="text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 font-medium"
            onClick={() => handleOpenModal(record)}
          >
            Edit
          </Button>
          <Popconfirm
            title="Hapus Layanan"
            description={`Apakah Anda yakin ingin menghapus "${record.title}"?`}
            onConfirm={() => handleDelete(record.id)}
            okText="Ya, Hapus"
            cancelText="Batal"
            okButtonProps={{ danger: true, className: 'font-medium' }}
            cancelButtonProps={{ className: 'font-medium' }}
          >
            <Button 
              type="text" 
              danger 
              icon={<DeleteOutlined />}
              className="font-medium"
            >
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <>
      <Card 
        className="shadow-sm border border-slate-200 rounded-xl" 
        styles={{ body: { padding: '24px' } }}
      >
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6">
          <div>
            <Title level={4} className={`${plusJakartaSans.className} m-0 text-slate-800`}>
              Services Management
            </Title>
            <p className="text-slate-500 mt-1">Kelola data layanan yang ditampilkan di website.</p>
          </div>
          <Button 
            type="primary" 
            icon={<PlusOutlined />} 
            className="bg-cyan-500 hover:bg-cyan-400 border-0 h-10 px-5 rounded-lg shadow-md shadow-cyan-500/20 font-semibold tracking-wide self-start sm:self-auto"
            onClick={() => handleOpenModal()}
          >
            Add New Service
          </Button>
        </div>

        <ResponsiveTable>
          <Table 
            columns={columns} 
            dataSource={data} 
            rowKey="id"
            pagination={{ pageSize: 10, className: 'mt-6' }}
            className="border border-slate-100 rounded-xl overflow-hidden [&_.ant-table-thead_th]:bg-slate-50 [&_.ant-table-thead_th]:text-slate-500 [&_.ant-table-thead_th]:font-semibold"
          />
        </ResponsiveTable>
      </Card>

      {/* MODAL FORM CREATE/EDIT */}
      <Modal
        title={<span className={`${plusJakartaSans.className} text-xl text-slate-800`}>{editingId ? 'Edit Service' : 'Add New Service'}</span>}
        open={isModalOpen}
        onCancel={handleCloseModal}
        footer={null}
        width={640}
        destroyOnHidden
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={onFinish}
          className="mt-6"
          size="large"
          initialValues={{ status: 'PUBLISHED' }}
        >
          <Form.Item
            name="title"
            label={<span className="font-semibold text-slate-700">Nama Layanan</span>}
            rules={[{ required: true, message: 'Harap masukkan nama layanan' }]}
          >
            <Input placeholder="Misal: Cloud Solutions" onChange={handleTitleChange} className="rounded-lg" />
          </Form.Item>

          <Form.Item
            name="slug"
            label={<span className="font-semibold text-slate-700">Slug URL</span>}
            rules={[{ required: true, message: 'Slug tidak boleh kosong' }]}
          >
            <Input 
              placeholder="cloud-solutions" 
              className="rounded-lg bg-slate-50" 
              onChange={() => setIsSlugAutoGenerated(false)}
            />
          </Form.Item>

          <Form.Item
            name="description"
            label={<span className="font-semibold text-slate-700">Deskripsi Layanan</span>}
            rules={[{ required: true, message: 'Harap masukkan deskripsi layanan' }]}
          >
            <TextArea rows={5} placeholder="Jelaskan detail layanan yang ditawarkan..." className="rounded-lg" />
          </Form.Item>

          <Form.Item
            label={<span className="font-semibold text-slate-700">Ikon Layanan</span>}
          >
            <div className="flex gap-2 items-start">
              {useCustomIcon ? (
                <>
                  <Form.Item name="customIcon" noStyle>
                    <Input
                      placeholder="https://example.com/icon.svg atau URL gambar"
                      className="rounded-lg flex-1"
                      prefix={<LinkOutlined className="text-slate-400" />}
                    />
                  </Form.Item>
                  <Button
                    onClick={() => { setUseCustomIcon(false); form.setFieldsValue({ customIcon: '' }); }}
                    size="large"
                    className="rounded-lg flex-shrink-0 text-slate-600"
                    title="Kembali ke pilihan ikon"
                  >
                    ← Pilih
                  </Button>
                </>
              ) : (
                <>
                  <Form.Item name="image" noStyle>
                    <Select
                      placeholder="Pilih ikon emoji"
                      className="flex-1"
                      allowClear
                      options={ICON_OPTIONS}
                      optionRender={(option) => (
                        <div className="flex items-center gap-2">
                          <span className="text-2xl">{option.value}</span>
                          <span className="text-slate-600">{option.label}</span>
                        </div>
                      )}
                    />
                  </Form.Item>
                  <Button
                    type="primary"
                    icon={<PlusOutlined />}
                    size="large"
                    onClick={() => { setUseCustomIcon(true); form.setFieldsValue({ image: undefined }); }}
                    className="flex-shrink-0 bg-slate-800 hover:bg-slate-700"
                    title="Masukkan URL icon kustom"
                  />
                </>
              )}
            </div>
            <p className="text-xs text-slate-400 mt-1.5">
              {useCustomIcon ? 'Masukkan URL gambar atau SVG untuk ikon layanan.' : 'Pilih emoji atau klik + untuk URL icon kustom.'}
            </p>
          </Form.Item>

          <Form.Item
            name="status"
            label={<span className="font-semibold text-slate-700">Status</span>}
          >
            <Select className="rounded-lg">
              <Select.Option value="PUBLISHED">Published</Select.Option>
              <Select.Option value="DRAFT">Draft</Select.Option>
            </Select>
          </Form.Item>

          <div className="flex justify-end gap-3 mt-6 pt-5 border-t border-slate-100">
            <Button size="large" onClick={handleCloseModal} className="rounded-lg font-medium">
              Batal
            </Button>
            <Button type="primary" htmlType="submit" size="large" className="bg-slate-900 hover:bg-slate-800 border-0 rounded-lg font-medium px-8 shadow-lg shadow-slate-900/20">
              Simpan
            </Button>
          </div>
        </Form>
      </Modal>
    </>
  );
}
