'use client';

import React, { useState } from 'react';
import { Table, Button, Popconfirm, Tag, Space, Typography, Card, Modal, Form, Input, Select, Upload, message } from 'antd';
import { EditOutlined, DeleteOutlined, PlusOutlined, InboxOutlined } from '@ant-design/icons';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { createService, updateService, deleteService, getService } from './actions';
import ResponsiveTable from '@/components/ResponsiveTable';

const { Title } = Typography;
const { TextArea } = Input;
const { Dragger } = Upload;

const plusJakartaSans = Plus_Jakarta_Sans({ 
  subsets: ['latin'], 
  weight: ['600', '700'],
  display: 'swap',
});

export interface ServiceData {
  id: string;
  title: string;
  status: string;
  updatedAt: Date;
}

interface ServicesTableProps {
  data: ServiceData[];
}

export default function ServicesTable({ data }: ServicesTableProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form] = Form.useForm();
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);

  const handleOpenModal = async (record?: ServiceData) => {
    setIsModalOpen(true);
    if (record) {
      setEditingId(record.id);
      setIsSlugAutoGenerated(false);
      const res = await getService(record.id);
      if (res.success && res.data) {
        const fullData = res.data;

        // Ubah string URL gambar menjadi format fileList Ant Design
        const fileList = fullData.image ? [{
          uid: '-1',
          name: fullData.image.split('/').pop() || 'image.png',
          status: 'done',
          url: fullData.image,
        }] : [];

        setTimeout(() => form.setFieldsValue({
          ...fullData,
          image: fileList,
        }), 0);
      } else {
        setTimeout(() => form.setFieldsValue(record), 0);
      }
    } else {
      setEditingId(null);
      setIsSlugAutoGenerated(true);
      setTimeout(() => form.resetFields(), 0);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    form.resetFields();
    setEditingId(null);
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isSlugAutoGenerated) {
      const value = e.target.value;
      const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
      form.setFieldsValue({ slug });
    }
  };

  const handleDelete = async (id: string) => {
    const res = await deleteService(id);
    if (res.success) {
      message.success('Layanan berhasil dihapus');
    } else {
      message.error(res.error || 'Gagal menghapus layanan');
    }
  };

  const handleUpload = async ({ file, onSuccess, onError }: any) => {
    const formData = new FormData();
    formData.append('file', file);

    try {
      const res = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });

      if (!res.ok) throw new Error('Upload gagal');
      const responseData = await res.json();
      
      onSuccess(responseData, file);
      message.success(`${file.name} berhasil diunggah`);
    } catch (err) {
      console.error(err);
      onError(err);
      message.error(`${file.name} gagal diunggah`);
    }
  };

  const onFinish = async (values: any) => {
    // Ekstrak string URL dari array fileList
    const fileList = values.image || [];
    let imageUrl = null;
    if (fileList.length > 0) {
      const file = fileList[0];
      if (file.url) imageUrl = file.url;
      else if (file.response && file.response.secure_url) imageUrl = file.response.secure_url;
    }

    const submitData = {
      ...values,
      image: imageUrl,
    };

    let res;
    if (editingId) {
      res = await updateService(editingId, submitData);
    } else {
      res = await createService(submitData);
    }

    if (res.success) {
      message.success('Layanan berhasil disimpan!');
      handleCloseModal();
    } else {
      message.error(res.error || 'Gagal menyimpan layanan');
    }
  };

  const columns = [
    {
      title: 'Nama Layanan',
      dataIndex: 'title',
      key: 'title',
      render: (text: string) => <span className="font-semibold text-slate-800">{text}</span>,
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => {
        const color = status === 'PUBLISHED' ? 'green' : status === 'DRAFT' ? 'gold' : 'blue';
        return <Tag color={color} className="font-semibold px-3 py-1 rounded-md tracking-wide">{status}</Tag>;
      },
    },
    {
      title: 'Updated At',
      dataIndex: 'updatedAt',
      key: 'updatedAt',
      render: (date: Date) => (
        <span className="text-slate-500 font-medium">
          {new Date(date).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}
        </span>
      ),
    },
    {
      title: 'Aksi',
      key: 'action',
      render: (_: any, record: ServiceData) => (
        <Space size="small">
          <Button 
            type="text" 
            icon={<EditOutlined />} 
            className="text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 font-medium"
            onClick={() => handleOpenModal(record)}
          >
            Edit
          </Button>
          <Popconfirm
            title="Hapus Layanan"
            description={`Apakah Anda yakin ingin menghapus "${record.title}"?`}
            onConfirm={() => handleDelete(record.id)}
            okText="Ya, Hapus"
            cancelText="Batal"
            okButtonProps={{ danger: true, className: 'font-medium' }}
            cancelButtonProps={{ className: 'font-medium' }}
          >
            <Button 
              type="text" 
              danger 
              icon={<DeleteOutlined />}
              className="font-medium"
            >
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <>
      <Card 
        className="shadow-sm border border-slate-200 rounded-xl" 
        styles={{ body: { padding: '24px' } }}
      >
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6">
          <div>
            <Title level={4} className={`${plusJakartaSans.className} m-0 text-slate-800`}>
              Services Management
            </Title>
            <p className="text-slate-500 mt-1">Kelola data layanan yang ditampilkan di website.</p>
          </div>
          <Button 
            type="primary" 
            icon={<PlusOutlined />} 
            className="bg-cyan-500 hover:bg-cyan-400 border-0 h-10 px-5 rounded-lg shadow-md shadow-cyan-500/20 font-semibold tracking-wide self-start sm:self-auto"
            onClick={() => handleOpenModal()}
          >
            Add New Service
          </Button>
        </div>

        <ResponsiveTable>
          <Table 
            columns={columns} 
            dataSource={data} 
            rowKey="id"
            pagination={{ pageSize: 10, className: 'mt-6' }}
            className="border border-slate-100 rounded-xl overflow-hidden [&_.ant-table-thead_th]:bg-slate-50 [&_.ant-table-thead_th]:text-slate-500 [&_.ant-table-thead_th]:font-semibold"
          />
        </ResponsiveTable>
      </Card>

      {/* MODAL FORM CREATE/EDIT */}
      <Modal
        title={<span className={`${plusJakartaSans.className} text-xl text-slate-800`}>{editingId ? 'Edit Service' : 'Add New Service'}</span>}
        open={isModalOpen}
        onCancel={handleCloseModal}
        footer={null}
        width={640}
        destroyOnHidden
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={onFinish}
          className="mt-6"
          size="large"
          initialValues={{ status: 'PUBLISHED' }}
        >
          <Form.Item
            name="title"
            label={<span className="font-semibold text-slate-700">Nama Layanan</span>}
            rules={[{ required: true, message: 'Harap masukkan nama layanan' }]}
          >
            <Input placeholder="Misal: Cloud Solutions" onChange={handleTitleChange} className="rounded-lg" />
          </Form.Item>

          <Form.Item
            name="slug"
            label={<span className="font-semibold text-slate-700">Slug URL</span>}
            rules={[{ required: true, message: 'Slug tidak boleh kosong' }]}
          >
            <Input 
              placeholder="cloud-solutions" 
              className="rounded-lg bg-slate-50" 
              onChange={() => setIsSlugAutoGenerated(false)}
            />
          </Form.Item>

          <Form.Item
            name="description"
            label={<span className="font-semibold text-slate-700">Deskripsi Layanan</span>}
            rules={[{ required: true, message: 'Harap masukkan deskripsi layanan' }]}
          >
            <TextArea rows={5} placeholder="Jelaskan detail layanan yang ditawarkan..." className="rounded-lg" />
          </Form.Item>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6">
            <Form.Item
              name="image"
              label={<span className="font-semibold text-slate-700">Gambar / Ikon Layanan</span>}
              valuePropName="fileList"
              getValueFromEvent={(e) => {
                if (Array.isArray(e)) return e;
                return e?.fileList;
              }}
            >
              <Dragger
                customRequest={handleUpload}
                maxCount={1}
                listType="picture"
                className="bg-slate-50 border-slate-300"
              >
                <p className="ant-upload-drag-icon">
                  <InboxOutlined className="text-cyan-500" />
                </p>
                <p className="ant-upload-text font-semibold text-slate-700">Click or drag file to this area to upload</p>
                <p className="ant-upload-hint text-slate-500 text-xs px-2">
                  Unggah 1 gambar/ikon layanan.
                </p>
              </Dragger>
            </Form.Item>

            <Form.Item
              name="status"
              label={<span className="font-semibold text-slate-700">Status</span>}
            >
              <Select className="rounded-lg">
                <Select.Option value="PUBLISHED">Published</Select.Option>
                <Select.Option value="DRAFT">Draft</Select.Option>
              </Select>
            </Form.Item>
          </div>

          <div className="flex justify-end gap-3 mt-6 pt-5 border-t border-slate-100">
            <Button size="large" onClick={handleCloseModal} className="rounded-lg font-medium">
              Batal
            </Button>
            <Button type="primary" htmlType="submit" size="large" className="bg-slate-900 hover:bg-slate-800 border-0 rounded-lg font-medium px-8 shadow-lg shadow-slate-900/20">
              Simpan
            </Button>
          </div>
        </Form>
      </Modal>
    </>
  );
}
