'use client';

import React, { useState, useEffect } from 'react';
import { Form, Input, Button, Card, Typography, Select, message } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { useRouter } from 'next/navigation';
import dynamic from 'next/dynamic';
import 'react-quill-new/dist/quill.snow.css';
import { createBlog, updateBlog } from '../actions';

// Disable SSR for React-Quill to avoid document not defined error
const ReactQuill = dynamic(() => import('react-quill-new'), { ssr: false });

const { Title } = Typography;

const plusJakartaSans = Plus_Jakarta_Sans({ 
  subsets: ['latin'], 
  weight: ['600', '700'],
  display: 'swap',
});

interface BlogFormProps {
  initialData: any | null;
}

export default function BlogForm({ initialData }: BlogFormProps) {
  const [form] = Form.useForm();
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(!initialData);
  const [contentValue, setContentValue] = useState(initialData?.content || '');

  useEffect(() => {
    if (initialData) {
      form.setFieldsValue(initialData);
      setContentValue(initialData.content || '');
    }
  }, [initialData, form]);

  const handleContentChange = (value: string) => {
    // Quill sends '<p><br></p>' for empty content
    const isEmpty = !value || value === '<p><br></p>';
    setContentValue(value);
    form.setFieldsValue({ content: isEmpty ? '' : value });
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isSlugAutoGenerated) {
      const value = e.target.value;
      const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
      form.setFieldsValue({ slug });
    }
  };

  const handleSlugChange = () => {
    // If the user manually edits the slug, stop auto-generating it from title
    setIsSlugAutoGenerated(false);
  };

  const onFinish = async (values: any) => {
    setIsSubmitting(true);
    let res;
    if (initialData) {
      res = await updateBlog(initialData.id, values);
    } else {
      res = await createBlog(values);
    }

    setIsSubmitting(false);

    if (res.success) {
      message.success('Artikel berhasil disimpan!');
      router.push('/admin/dashboard/blog');
    } else {
      message.error(res.error || 'Gagal menyimpan artikel');
    }
  };

  return (
    <>
      <Button 
        type="text" 
        icon={<ArrowLeftOutlined />} 
        onClick={() => router.push('/admin/dashboard/blog')}
        className="mb-4 text-slate-500 hover:text-slate-800 font-medium"
      >
        Kembali ke Daftar Blog
      </Button>

      <Card 
        className="shadow-sm border border-slate-200 rounded-xl" 
        styles={{ body: { padding: '32px' } }}
      >
        <div className="mb-8 border-b border-slate-100 pb-6">
          <Title level={3} className={`${plusJakartaSans.className} m-0 text-slate-800`}>
            {initialData ? 'Edit Artikel' : 'Tulis Artikel Baru'}
          </Title>
          <p className="text-slate-500 mt-1">Gunakan editor di bawah ini untuk membuat artikel yang informatif dan SEO-friendly.</p>
        </div>

        <Form
          form={form}
          layout="vertical"
          onFinish={onFinish}
          size="large"
          initialValues={{ status: 'DRAFT', author: 'Admin' }}
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6">
            <Form.Item
              name="title"
              label={<span className="font-semibold text-slate-700">Judul Artikel</span>}
              rules={[{ required: true, message: 'Harap masukkan judul artikel' }]}
            >
              <Input 
                placeholder="Misal: Tren Teknologi Cloud di 2026" 
                onChange={handleTitleChange}
                className="rounded-lg" 
              />
            </Form.Item>

            <Form.Item
              name="slug"
              label={<span className="font-semibold text-slate-700">Slug URL</span>}
              rules={[{ required: true, message: 'Slug tidak boleh kosong' }]}
            >
              <Input 
                placeholder="Misal: tren-teknologi-cloud-di-2026" 
                onChange={handleSlugChange}
                className="rounded-lg bg-slate-50" 
              />
            </Form.Item>

            <Form.Item
              name="author"
              label={<span className="font-semibold text-slate-700">Penulis</span>}
              rules={[{ required: true, message: 'Harap masukkan nama penulis' }]}
            >
              <Input placeholder="Nama penulis artikel" className="rounded-lg" />
            </Form.Item>

            <Form.Item
              name="status"
              label={<span className="font-semibold text-slate-700">Status Publikasi</span>}
            >
              <Select className="rounded-lg">
                <Select.Option value="DRAFT">Draft</Select.Option>
                <Select.Option value="PUBLISHED">Published</Select.Option>
                <Select.Option value="ARCHIVED">Archived</Select.Option>
              </Select>
            </Form.Item>
          </div>

          <Form.Item
            name="content"
            label={<span className="font-semibold text-slate-700">Konten Artikel</span>}
            rules={[{ required: true, message: 'Konten artikel tidak boleh kosong' }]}
            className="mb-8"
          >
            <div className="border border-slate-200 rounded-lg overflow-hidden">
              <ReactQuill 
                theme="snow" 
                value={contentValue}
                onChange={handleContentChange}
                placeholder="Tulis konten Anda di sini..."
                style={{ height: '300px', backgroundColor: 'white' }}
                modules={{
                  toolbar: [
                    [{ 'header': [1, 2, 3, false] }],
                    ['bold', 'italic', 'underline', 'strike', 'blockquote'],
                    [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
                    ['link', 'image'],
                    ['clean']
                  ],
                }}
              />
            </div>
          </Form.Item>

          <div className="flex justify-end gap-3 pt-6 mt-12 border-t border-slate-100">
            <Button 
              size="large" 
              onClick={() => router.push('/admin/dashboard/blog')} 
              className="rounded-lg font-medium"
            >
              Batal
            </Button>
            <Button 
              type="primary" 
              htmlType="submit" 
              size="large" 
              loading={isSubmitting}
              className="bg-slate-900 hover:bg-slate-800 border-0 rounded-lg font-medium px-8 shadow-lg shadow-slate-900/20"
            >
              {initialData ? 'Update Artikel' : 'Publikasi Artikel'}
            </Button>
          </div>
        </Form>
      </Card>
    </>
  );
}
